
services:
  
  # trabalho_nest:
  #   image: moises2023014223/trabalho:latest
  #   container_name: trabalho_node
  #   command: >
  #     sh -c "dockerize -wait tcp://db:5432 -timeout 20s &&
  #     npm install &&
  #     npx prisma generate &&
  #     npx prisma migrate dev &&
  #     npm run start:dev"
  #   tty: true
  #   ports: 
  #     - 3000:3000
  #   networks:
  #     - trabalho_network
  #   depends_on: 
  #      - db
  trabalho_nest:
    image: moises2023014223/trabalho-next-prod:latest
    container_name: trabalho_node
    command: >
      sh -c "dockerize -wait tcp://db:5432 -timeout 30s &&
      npx prisma generate &&
      npx prisma migrate dev &&
      node dist/main"
    tty: true
    networks:
      - trabalho_network
    depends_on: 
       - db
  trabalho-nginx:
    image: nginx:alpine
    container_name: trabalho-nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - trabalho_nest
    networks:
      - trabalho_network

  db:
    container_name: db
    image: postgres:15-alpine
    restart: unless-stopped 
    ports:
      - 5432:5432
    tty: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fudamentos-backend
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
    networks:
        - trabalho_network

networks:
  trabalho_network:
    driver: bridge